
---
kind: Service
metadata:
  name: jekyll
  namespace: development
spec:
  type: NodePort
  selector:
   run: jekyll
  ports:
    - port: 8080
      targetPort: 4000
      # Optional field
       #range (default: 30000-32767)
      nodePort: 30097
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jekyll-site
  namespace: development
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage

